title = "mallya's blog"
baseURL = 'https://xeon.me/'

languageCode = 'en-us'
defaultContentLanguage = "en-gb"

enableEmoji = true

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

############################## English language ################################
[Languages.en-gb]
  languageName = "English"
  languageCode = "en-gb"
  contentDir = "content/"
  weight = 1

  [Languages.en-gb.menu]
  [[Languages.en-gb.menu.main]]
    pageRef = "/"
    name = 'Home'
    url = '/'
    weight = 10
  [[Languages.en-gb.menu.main]]
    pageRef = "posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[Languages.en-gb.menu.main]]
    pageRef = "about"
    name = 'About'
    url = '/about/'
    weight = 30

[Languages.en-gb.params]
  sitename = "mallya's blog"
  description = "I write about whatever I am doing here. Mostly programming, but anything goes."
  mainSections = ['posts', 'gnome']

[Languages.en-gb.params.author]
  name = "Varun R Mallya"
  description = "I write about stuff here. Mostly software related, but expect the unexpected. Also, Gnome stuff."

[[params.socialIcons]]
name = "github"
url = "https://github.com/varun-r-mallya"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/SDLRenderer"
